# Generated by Django 4.2.2 on 2023-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0009_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='state',
        ),
        migrations.AddField(
            model_name='text',
            name='status',
            field=models.CharField(choices=[('W', '(W) Not translated'), ('L', '(L) Translated & Not reviewed'), ('E', ' (E) Reviewed & Editable'), ('W', ' (V) Translated')], default='W', help_text='Enter the translation status', max_length=1),
        ),
    ]
