# Generated by Django 4.2.2 on 2023-06-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0008_authortype_author_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Enter the name of author', max_length=100),
        ),
    ]
