# Generated by Django 4.2.2 on 2023-06-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0010_remove_text_state_text_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='status',
            field=models.CharField(choices=[('W', 'Not translated'), ('L', 'Translated & Not reviewed'), ('E', 'Reviewed & Editable'), ('V', 'Translated')], default='W', help_text='Enter the translation status', max_length=1),
        ),
    ]
