# Generated by Django 4.2.2 on 2023-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='text',
            name='author',
        ),
        migrations.AddField(
            model_name='text',
            name='authors',
            field=models.ManyToManyField(blank=True, to='app_tracoll.author'),
        ),
    ]
