# Generated by Django 4.2.2 on 2023-06-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0011_alter_text_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['title'], 'permissions': (('is_translated', 'Set text as translated'),)},
        ),
    ]
