# Generated by Django 4.2.2 on 2023-06-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0012_alter_text_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['title'], 'permissions': (('is_translated', 'Set text as translated'), ('all_texts', 'Show texts translated and not translated'))},
        ),
    ]
