# Generated by Django 4.2.2 on 2023-06-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0013_alter_text_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='status',
            field=models.CharField(choices=[('W', 'Not translated'), ('L', 'Translation not reviewed'), ('E', 'Translation reviewed (& editable)'), ('V', 'Translation')], default='W', help_text='Enter the translation status', max_length=1),
        ),
    ]
