# Generated by Django 4.2.2 on 2023-06-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0002_alter_author_options_remove_text_author_text_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='language',
        ),
        migrations.RemoveField(
            model_name='text',
            name='type',
        ),
    ]
