# Generated by Django 4.2.2 on 2023-06-13 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0004_language_type_text_language_text_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tracoll.language'),
        ),
        migrations.AlterField(
            model_name='text',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tracoll.type'),
        ),
    ]
