# Generated by Django 4.2.2 on 2023-06-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracoll', '0007_texttype_remove_author_type_alter_language_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the author type: poet, singer, band...', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Enter the type of author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tracoll.authortype'),
        ),
    ]
